apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t04thal0p-go
  janus-idp.io/tekton: t04thal0p-go
  backstage.io/kubernetes-id: t04thal0p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t04thal0p-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
